### ISSUE TITLE
Can't install the theme

### ISSUE THREAD

**Issue by joaocandre** [hdni/Phosphene#11]
Downloaded the .zip, extracted to /usr/share/themes, copied the gtk-2.0 from another theme (Numix) as instrcted, however after setting the theme this is what I get: 

![screenshot from 2013-12-02 19 16 31](https://f.cloud.github.com/assets/1812344/1657669/ca007c06-5b86-11e3-8205-cbc462da6e69.png)

Running Archlinux up to date and Gnome Shell 3.10. Any idea why this is happening? Thanks in advance.

**Comment by hdni** [comment]
That's really weird man, could you upload your theme directory so I can have a look? I'm using Arch too so as long as you're up to date that shouldn't be a problem.

**Comment by joaocandre** [comment]
Sure! Here it goes: https://www.mediafire.com/?65e0u6zkyes84h6

**Comment by hdni** [comment]
Well, your Phosphene folder actually works for me, so at least that's not the problem. Do you have gnome-themes-standard installed (you seem to), and does Adwaita work?

**Comment by joaocandre** [comment]
Yes, I do have gnome-themes-standard installed, and the Adwaita theme works.

**Comment by hdni** [comment]
OK, could you check if you have gtk-engine-murrine installed then? You can also set Numix through the Tweak Tool and see if it works.

**Comment by joaocandre** [comment]
Yes, and I am using Numix as my theme right now.

**Comment by hdni** [comment]
How about the permissions/owner of the Phosphene folder and of the directories inside it? If that isn't it then I don't really have a clue.

**Comment by joaocandre** [comment]
```
[joao@joao-arch themes]$ ls -las
total 68
4 drwxr-xr-x  17 root root 4096 Dec  2 19:12 .
4 drwxr-xr-x 210 root root 4096 Dec  3 21:11 ..
4 drwxr-xr-x   6 root root 4096 Dec  3 21:08 Adwaita
4 drwxr-xr-x   3 root root 4096 Jun 11  2012 Clearlooks
4 drwxr-xr-x   3 root root 4096 Jun 11  2012 Crux
4 drwxr-xr-x   4 root root 4096 Nov 26 19:21 Default
4 drwxr-xr-x   4 root root 4096 Nov 26 19:21 Emacs
4 drwxr-xr-x   5 root root 4096 Dec  3 21:08 HighContrast
4 drwxr-xr-x   3 root root 4096 Jun 11  2012 Industrial
4 drwxr-xr-x   3 root root 4096 Jun 11  2012 Mist
4 drwxr-xr-x   9 root root 4096 Dec  1 02:53 Numix
4 drwxr-xr-x   6 root root 4096 Dec  1 02:48 NumixBLUE
4 drwxr-xr-x   7 root root 4096 Dec  2 18:47 Orion
4 drwxr-xr-x   6 root root 4096 Dec  2 19:13 Phosphene
4 drwxr-xr-x   3 root root 4096 Oct 11 15:13 Raleigh
4 drwxr-xr-x   3 root root 4096 Jun 11  2012 Redmond
4 drwxr-xr-x   3 root root 4096 Jun 11  2012 ThinIce
[joao@joao-arch themes]$ ls -las Phosphene/
total 52
 4 drwxr-xr-x  6 root root  4096 Dec  2 19:13 .
 4 drwxr-xr-x 17 root root  4096 Dec  2 19:12 ..
24 -rw-r--r--  1 root root 21659 Dec  2 19:12 firefox.css
 4 drwx------  3 root root  4096 Dec  2 19:12 gnome-shell
 4 drwxr-xr-x  2 root root  4096 Dec  2 19:13 gtk-2.0
 4 drwx------  3 root root  4096 Dec  2 19:12 gtk-3.0
 4 drwx------  3 root root  4096 Dec  2 19:12 metacity-1
 4 -rw-r--r--  1 root root  2037 Dec  2 19:12 README.md
[joao@joao-arch themes]$ ls -las Numix/
total 44
4 drwxr-xr-x  9 root root 4096 Dec  1 02:53 .
4 drwxr-xr-x 17 root root 4096 Dec  2 19:12 ..
4 drwxr-xr-x  2 root root 4096 Dec  1 02:53 gtk-2.0
4 drwxr-xr-x  4 root root 4096 Dec  1 02:53 gtk-3.0
4 -rw-r--r--  1 root root  187 Dec  1 02:53 index.theme
4 drwxr-xr-x  2 root root 4096 Dec  1 02:53 metacity-1
4 drwxr-xr-x  2 root root 4096 Dec  1 02:53 openbox-3
4 -rw-r--r--  1 root root  777 Dec  1 02:53 README.md
4 drwxr-xr-x  2 root root 4096 Dec  1 02:53 unity
4 drwxr-xr-x  2 root root 4096 Dec  1 02:53 xfce-notify-4.0
4 drwxr-xr-x  2 root root 4096 Dec  1 02:53 xfwm4
```

There seems to be something different between, for example, the gtk-2.0 and the gtfk-3.0 folders inside the Phosphene folder.

**Comment by hdni** [comment]
Yeah, it's a permission problem; I should have thought about it sooner. You can see that the gnome-shell, gtk-3.0 and metacity-1 folders are owned by root, and only root has the permissions to read the themes:

> 4 drwx------ 3 root root 4096 Dec 2 19:12 gnome-shell
> 4 drwx------ 3 root root 4096 Dec 2 19:12 gtk-3.0
> 4 drwx------ 3 root root 4096 Dec 2 19:12 metacity-1

Go in `/usr/share/themes/Phosphene` and run this: 

```
sudo chmod 755 {gnome-shell,gtk-3.0,metacity-1}
```

That should fix your issue by allowing all users to read the theme.

**Comment by joaocandre** [comment]
That fixed, thanks :)

**Comment by hdni** [comment]
Great!
