### ISSUE TITLE
GTK-2 apps have dark bar underneath title bar

### ISSUE THREAD

**Issue by davejacobs** [hdni/Phosphene#12]
I just installed this theme and love it, thank you! I moved the Adwaita GTK-2 theme into the Phosphene directory and activated it, per https://github.com/hdni/Phosphene/issues/1. However, some (GTK-2 HIG) apps look very bad:

![screenshot from 2013-12-05 20 22 46](https://f.cloud.github.com/assets/10695/1689791/d4c724e2-5e2d-11e3-9c10-fda06cd0fb91.png)

You'll notice that not only is the window theme different (presumably because it is using GTK-2 layouts, namely "Finery"), but the menubar and controls look very bad (unstyled?). I don't think this is just a problem with Phosphene, but the default theme Adwaita doesn't have this problem. Any idea what I could do to get rid of this issue?

**Comment by hdni** [comment]
Looks like it's not even using Adwaita, but (I think) Raleigh, the fallback theme. The issue doesn't seem related to Phosphene itself since, as you mentioned, it doesn't affect GTK 2, so make sure your permissions are OK -- see #11.
I haven't run into this problem myself, it seems weird that it wouldn't even use the window decorations.

**Comment by davejacobs** [comment]
Nevermind, fixed the problem -- thanks for the help!

**Comment by evanpurkhiser** [comment]
So [don't leave us in the dark here](http://xkcd.com/979/)! How did you solve it?

**Comment by davejacobs** [comment]
My particular problem was that I miscopied the directory -- apparently the gtk-2.0 directory already existed in the theme (because I had fiddled around with it before) and so when I copied in the Adwaita gtk-2.0 directory, it went into the directory instead of replacing it. So ... user error :)

**Comment by hdni** [comment]
I wanted to ask what the problem was, but looks like Evan beat me to it. Good to know!
