### ISSUE TITLE
giant icons in systray

### ISSUE THREAD

**Issue by hadenodom** [hdni/Phosphene#13]
![screenshot - 12072013 - 08 05 18 pm](https://f.cloud.github.com/assets/5101247/1699593/c3fd9a66-5fad-11e3-8351-abab02572f93.png)
Not sure what could be causing this, but basically, as soon as I installed phosphene, all the icons in my systray turned into giant icons.  Picture related.

Any ideas?

**Comment by hdni** [comment]
See #9.
If you aren't using Gnome 3.10, you should use the previous version of Phosphene for 3.8:
https://github.com/hdni/Phosphene/tree/190338736be98c914d53fb789140930584b019ea

**Comment by hadenodom** [comment]
Sorry, I didn't see the previous issue (#9).. I should've looked.  I'm going to install 3.10 then.

**Comment by hdni** [comment]
It's nothing, don't worry. Your issue's title might be a bit more obvious when people scan through the closed issues.
