### ISSUE TITLE
Huge toolbar in the upper right corner

### ISSUE THREAD

**Issue by ghost** [hdni/Phosphene#15]
![screenshot from 2013-12-13 07 02 57](https://f.cloud.github.com/assets/1129680/1740140/54c06ddc-63bc-11e3-8413-ecb1a21204e9.png)

Love this theme. But the upper right corners icons looks messed up. They are WAY to big. I have never modified Gnome shell themes so I'm thinking something in my config is messing it up.

However, that's what it looks like.

Best regards.

**Comment by evanpurkhiser** [comment]
See #9, #10, and #13

**Comment by ghost** [comment]
Thanks, worked great.

**Comment by hdni** [comment]
Thanks for your help, Evan.
