### ISSUE TITLE
No close button in the Firefox theme.

### ISSUE THREAD

**Issue by ghost** [hdni/Phosphene#17]
I dont have a close button for the tabs in the firefox theme. As soon as I turn off the theme so it will look like Chrome, the buttons show up again.

The pictures describes it better.

![screenshot from 2013-12-20 11 36 28](https://f.cloud.github.com/assets/1129680/1789793/318c95e6-6963-11e3-9fe6-97d1ebb69cef.png)

![screenshot from 2013-12-20 11 40 02](https://f.cloud.github.com/assets/1129680/1789794/369ebd52-6963-11e3-9af5-f1b8381eaca6.png)

What do?

**Comment by evanpurkhiser** [comment]
Looks like you have two options:
1. Remove [this line](https://github.com/hdni/Phosphene/blob/master/firefox.css#L9) from firefox.css. Though it's not guaranteed this will look good and you may have to hack abit.
2. Get used to closing your tabs using a hotkey like <kbd>ctrl</kbd>+<kbd>w</kbd> or <kbd>ctrl</kbd>+<kbd>F4</kbd>.

I recommend the second option :wink:

**Comment by ghost** [comment]
Thanks! Worked great.
