### ISSUE TITLE
Infinality configuration?

### ISSUE THREAD

**Issue by evanpurkhiser** [hdni/Phosphene#4]
I saw on your [PF](http://pixelfuckers.org/submissions/2212) post you said you used infinality to get nice font rendering. Any chance you could add your configuration for that to the readme, or somewhere else?

**Comment by hdni** [comment]
Sure, I just put it in the [readme](https://github.com/hdni/dotfiles#infinality) of a more general repo, since it doesn't only apply to Phosphene.
